/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc.`in`.kotlin

import aoc.`in`.kotlin.utils.readInput

fun main() {
    println(dayOnePartOne(readInput("Day01")).toString())
    println(dayOnePartTwo(readInput("Day01")).toString())
}
