/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc.`in`.kotlin

import aoc.`in`.kotlin.utils.readInput

fun main() {
    //println(dayOnePartOne(readInput("Day01")).toString())
    //println(dayOnePartTwo(readInput("Day01")).toString())
    //println(dayTwoPartOne(readInput("Day02")).toString())
    //println(dayTwoPartTwo(readInput("Day02")).toString())
    //val (pagePrintOrder, pageOrderRule)= dayFiveSetup(readInput("Day05"))
    //println(dayFivePartOne(pagePrintOrder, pageOrderRule).toString())
    //println(dayFivePartTwo(pagePrintOrder, pageOrderRule).toString())
    //println(day03PartOne(readInput("Day03")).toString())
    println(day03PartTwo(readInput("Day03")).toString())
}
fun dayFiveSetup (input: List<String>): Pair<MutableList<List<Int>>,MutableList<List<Int>>> {
    val rule = mutableListOf<List<Int>>()
    val rows = mutableListOf<List<Int>>()
    input.forEach { line ->
        if (line.contains("|")) {
            val test = line.split("|").map { it.toInt() }
            rule.add(test)
        }
        if (line.contains(",")) {
            val test = line.split(",").map { it.toInt() }
            rows.add(test)
        }
    }
    return Pair(rule, rows)
}